#!/usr/bin/env bash
set -e

repo_root="$(git rev-parse --show-toplevel)"

cd "$repo_root"

echo "Checking C# files with StyleCop"
dotnet format Expressif.sln analyzers --verify-no-changes --no-restore
