#!/usr/bin/env bash
set -e

branch="$(git rev-parse --abbrev-ref HEAD)"

case "$branch" in
  feat/*|feature/*)
    echo "Running update-doc.ps1 on branch: $branch"
    ;;
  *)
    echo "Skipping update-doc.ps1 on branch: $branch"
    exit 0
    ;;
esac

pwsh -ExecutionPolicy Bypass -File "../generate-info.ps1" -class "function"
pwsh -ExecutionPolicy Bypass -File "../generate-info.ps1" -class "function" predicate
pwsh -ExecutionPolicy Bypass -File "../generate-info.ps1" -class "function" accumulator

#!/usr/bin/env bash
set -e

branch="$(git rev-parse --abbrev-ref HEAD)"

case "$branch" in
  feat/*|feature/*)
    ;;
  *)
    echo "Skipping pre-push check about documentation on branch: $branch"
    exit 0
    ;;
esac

echo "Updating language indexes for $branch"
pwsh -ExecutionPolicy Bypass -File "../generate-info.ps1" -Class "function"
pwsh -ExecutionPolicy Bypass -File "../generate-info.ps1" -Class "predicate"
pwsh -ExecutionPolicy Bypass -File "../generate-info.ps1" -Class "accumulator"

if [ -n "$(git status --porcelain)" ]; then
  echo "Generated documentation changes detected"

  echo "Updating Library index"
  pwsh -ExecutionPolicy Bypass -File "./update-index.ps1"
  echo "Updating docs"
  pwsh -ExecutionPolicy Bypass -File "./update-homepage.ps1"
  pwsh -ExecutionPolicy Bypass -File "./update-docs.ps1" function special
  pwsh -ExecutionPolicy Bypass -File "./update-docs.ps1" function text
  pwsh -ExecutionPolicy Bypass -File "./update-docs.ps1" function numeric
  pwsh -ExecutionPolicy Bypass -File "./update-docs.ps1" function temporal
  pwsh -ExecutionPolicy Bypass -File "./update-docs.ps1" function io
  pwsh -ExecutionPolicy Bypass -File "./update-docs.ps1" function array
  pwsh -ExecutionPolicy Bypass -File "./update-docs.ps1" accumulator array
  pwsh -ExecutionPolicy Bypass -File "./update-docs.ps1" predicate special
  pwsh -ExecutionPolicy Bypass -File "./update-docs.ps1" predicate text
  pwsh -ExecutionPolicy Bypass -File "./update-docs.ps1" predicate numeric
  pwsh -ExecutionPolicy Bypass -File "./update-docs.ps1" predicate temporal
  pwsh -ExecutionPolicy Bypass -File "./update-docs.ps1" predicate boolean
  pwsh -ExecutionPolicy Bypass -File "./update-examples.ps1" builder expression
  pwsh -ExecutionPolicy Bypass -File "./update-examples.ps1" builder predication
  pwsh -ExecutionPolicy Bypass -File "./update-examples.ps1" serializers
  echo "Updating README.md"
  pwsh -ExecutionPolicy Bypass -File "./update-readme.ps1" function
  pwsh -ExecutionPolicy Bypass -File "./update-readme.ps1" predicate
  pwsh -ExecutionPolicy Bypass -File "./update-readme.ps1" accumulator
  git add --all
  git status
  echo "Documentation changes detected. Please commit the changes before pushing the branch $branch."
  exit 1
else
  echo "No documentation changes detected for $branch"
  exit 0
fi
