# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site title and description
title:              Expressif
description:        Documentation of Expressif, a variable substitution engine with a rich library of functions and predicates
lang:               en

# Theme settings
theme:              just-the-docs

# Customizations for Just the Docs theme
logo: "/assets/images/expressif-logo-reversed.png"
favicon_ico: "/assets/images/favicon.ico"
color_scheme: expressif

just_the_docs:
  custom_css:
    - custom

defaults:
  -
    scope:
      path: "language"
    values:
      layout: docs
  -
    scope:
      path: "getting-started"
    values:
      layout: docs
  -
    scope:
      path: "functions"
    values:
      layout: docs
  -
    scope:
      path: "predicates"
    values:
      layout: docs
  -
    scope:
      path: "accumulators"
    values:
      layout: docs
  -
    scope:
      path: "cli"
    values:
      layout: docs
  -
    scope:
      path: "dotnet-sdk"
    values:
      layout: docs
  -
    scope:
      path: "tooling"
    values:
      layout: docs
  -
    scope:
      path: "download.md"
    values:
      layout: docs

# Aux links for the upper right navigation
aux_links:
  "Issue tracking":
    - "https://github.com/Seddryck/Expressif/issues"
  "View on GitHub":
    - "https://github.com/Seddryck/Expressif"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true


sass:
  quiet_deps: true

# Site subpath, e.g. /blog
baseurl: "/Expressif"
url: "http://127.0.0.1:4000"

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink:          /:title/


# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
  # Focus the search input by pressing `ctrl + focus_shortcut_key` (or `cmd + focus_shortcut_key` on macOS)
  focus_shortcut_key: 'k'

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true

# To use this feature, you need to configure a color and (optionally) title for each kind of callout
# you want to use in your documentation. Then, you can use the callouts in your markdown files like this:
# {: .warning }
# A paragraph...
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Recommended
    color: coffee
